-- MySQL Script generated by MySQL Workbench
-- Sat May 24 11:29:27 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db529314979
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db529314979` DEFAULT CHARACTER SET utf8 ;
USE `db529314979` ;

-- -----------------------------------------------------
-- Table `db529314979`.`CSCG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`CSCG` (
  `idCSCG` INT(11) NOT NULL AUTO_INCREMENT,
  `CSCGname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idCSCG`),
  UNIQUE INDEX `idCSCG_UNIQUE` (`idCSCG` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`dirname`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`dirname` (
  `idDirname` INT(11) NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idDirname`),
  UNIQUE INDEX `idDirname_UNIQUE` (`idDirname` ASC),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`documentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`documentation` (
  `idDocumentation` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `link` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`idDocumentation`),
  UNIQUE INDEX `idDocumentation_UNIQUE` (`idDocumentation` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`section` (
  `idSection` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`idSection`),
  UNIQUE INDEX `idSection_UNIQUE` (`idSection` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`type` (
  `idtype` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`idtype`),
  UNIQUE INDEX `idtype_UNIQUE` (`idtype` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`unit` (
  `idUnit` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idUnit`),
  UNIQUE INDEX `idUnit_UNIQUE` (`idUnit` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`fileFormat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`fileFormat` (
  `idFileFormat` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idFileFormat`),
  UNIQUE INDEX `idFileFormat_UNIQUE` (`idFileFormat` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`file` (
  `idFile` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `CSCG_idCSCG` INT(11) NOT NULL,
  `fileFormat_idFileFormat` INT(11) NOT NULL,
  `dirname_idDirname` INT(11) NOT NULL,
  PRIMARY KEY (`idFile`),
  UNIQUE INDEX `idFile_UNIQUE` (`idFile` ASC),
  INDEX `fk_file_CSCG1_idx` (`CSCG_idCSCG` ASC),
  INDEX `fk_file_fileFormat1_idx` (`fileFormat_idFileFormat` ASC),
  INDEX `fk_file_dirname1_idx` (`dirname_idDirname` ASC),
  CONSTRAINT `fk_file_CSCG1`
    FOREIGN KEY (`CSCG_idCSCG`)
    REFERENCES `db529314979`.`CSCG` (`idCSCG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_dirname1`
    FOREIGN KEY (`dirname_idDirname`)
    REFERENCES `db529314979`.`dirname` (`idDirname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_fileFormat1`
    FOREIGN KEY (`fileFormat_idFileFormat`)
    REFERENCES `db529314979`.`fileFormat` (`idFileFormat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 121
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`field` (
  `idField` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `min` INT(11) NULL DEFAULT NULL,
  `max` INT(11) NULL DEFAULT NULL,
  `unit_idUnit` INT(11) NOT NULL,
  `type_idtype` INT(11) NOT NULL,
  `section_idSection` INT(11) NOT NULL,
  `file_idFile` INT(11) NOT NULL,
  PRIMARY KEY (`idField`),
  UNIQUE INDEX `idField_UNIQUE` (`idField` ASC),
  INDEX `fk_field_unit1_idx` (`unit_idUnit` ASC),
  INDEX `fk_field_type1_idx` (`type_idtype` ASC),
  INDEX `fk_field_section1_idx` (`section_idSection` ASC),
  INDEX `fk_field_file1_idx` (`file_idFile` ASC),
  CONSTRAINT `fk_field_section1`
    FOREIGN KEY (`section_idSection`)
    REFERENCES `db529314979`.`section` (`idSection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `db529314979`.`type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_unit1`
    FOREIGN KEY (`unit_idUnit`)
    REFERENCES `db529314979`.`unit` (`idUnit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_field_file1`
    FOREIGN KEY (`file_idFile`)
    REFERENCES `db529314979`.`file` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`file_CSCG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`file_CSCG` (
  `CSCG_idCSCG` INT(11) NOT NULL,
  `file_idFile` INT(11) NOT NULL,
  INDEX `fk_file_CSCG_CSCG1_idx` (`CSCG_idCSCG` ASC),
  INDEX `fk_file_CSCG_file1_idx` (`file_idFile` ASC),
  CONSTRAINT `fk_file_CSCG_CSCG1`
    FOREIGN KEY (`CSCG_idCSCG`)
    REFERENCES `db529314979`.`CSCG` (`idCSCG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_CSCG_file1`
    FOREIGN KEY (`file_idFile`)
    REFERENCES `db529314979`.`file` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`file_documentation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`file_documentation` (
  `documentation_idDocumentation` INT(11) NOT NULL,
  `file_idFile` INT(11) NOT NULL,
  INDEX `fk_file_documentation_documentation1_idx` (`documentation_idDocumentation` ASC),
  INDEX `fk_file_documentation_file1_idx` (`file_idFile` ASC),
  CONSTRAINT `fk_file_documentation_documentation1`
    FOREIGN KEY (`documentation_idDocumentation`)
    REFERENCES `db529314979`.`documentation` (`idDocumentation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_documentation_file1`
    FOREIGN KEY (`file_idFile`)
    REFERENCES `db529314979`.`file` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`product` (
  `idProduct` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `version` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db529314979`.`file_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db529314979`.`file_product` (
  `file_idFile` INT(11) NOT NULL,
  `product_idProduct` INT(11) NOT NULL,
  INDEX `fk_file_product_file1_idx` (`file_idFile` ASC),
  INDEX `fk_file_product_product1_idx` (`product_idProduct` ASC),
  CONSTRAINT `fk_file_product_file1`
    FOREIGN KEY (`file_idFile`)
    REFERENCES `db529314979`.`file` (`idFile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_file_product_product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `db529314979`.`product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
